-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "retailer" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "purchaseAmount" TEXT;
